import type { Metadata } from "next";
import "../globals.css";
// 
export const metadata: Metadata = {
  title: "Crishi Ponno",
  icons: {
    icon: "https://res.cloudinary.com/dmbkgbtqj/image/upload/v1771485944/crishiponno/logo/crishiponno_hv6nym.jpg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
