import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/src/components/layout/navbar";
import Footer from "@/src/components/layout/footer";
//
export const metadata: Metadata = {
  title: "Crishi Ponno",
  icons:
    "https://res.cloudinary.com/dmbkgbtqj/image/upload/v1771485944/crishiponno/logo/crishiponno_hv6nym.jpg",
  description: "Generated by create next app",
};
//
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
