import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "../styles/globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import ReduxProvider from "@/components/utils/providers/ReduxProvider";
import Dialog from "@/components/utils/dialog";
import { Toaster } from "sonner";
import { DialogProvider } from "@/hooks/client/useDialog";
import Header from "@/components/layout/Header";
const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });
// import logo from "../../public/meta/logo.png";
//
export const metadata: Metadata = {
  title: "কৃষি পন্য",
  icons:
    "https://res.cloudinary.com/dmbkgbtqj/image/upload/v1789578379/crishi-ponno/logo/imgi_42_462211619_569007435482502_1193305002520903400_n_vy90h2.jpg",
  description: "Generated by create next app",
};
//
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", geist.variable)}
    >
      <body
        suppressHydrationWarning
        className="transition-colors duration-200 ease-in-out"
      >
        <ReduxProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <DialogProvider>
              <Header/>
              {children}
              <Dialog />
              <Toaster />
            </DialogProvider>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
